### ISSUE TITLE
Path to BioEn analyze executable on Mac

### ISSUE THREAD

**Issue by lukas-stelzl** [bio-phys/BioEn#1]
On my laptop I had problems with DEER example Jupyter notebook as it did not find the BioEn executable. I installed the BioEn package with the --user flag. 

> bioen

> -bash: bioen: command not found

The executable lives in  /Users/lukas/.local/bin/bioen, which is was not on my path. A simple fix was simple to add this folder to the path. The question is whether there is a more general fix.

**Comment by kain88-de** [comment]
Not if you install with the `--user` flag.  It will always depend on your path being set correctly which isn't done in a default installation. You can change the readme to recommend setting the path to `export PATH=$HOME/.local/bin:$PATH` or install the package in a conda-environment without the flag.

We can also look into making this a package available on conda if you like.

**Comment by lukas-stelzl** [comment]
Great, thanks, @kain88-de!
