### ISSUE TITLE
Leaked file descriptor in Deer observables class

### ISSUE THREAD

**Issue by kain88-de** [bio-phys/BioEn#2]
https://github.com/bio-phys/BioEn/blob/19277808e90738010eee5481548e0d0362a6aa20/bioen/analyze/observables/deer/deer.py#L42-L43

This line contains a leak. The call to `open` returns a file descriptor that is never closed again. This is OK when using only the `bioen` CLI tool. It will be a problem when using the library from python and analyzing a lot of deer data examples with `pkl_out` set because each process only is allowed a limited number of open file descriptors. The correct solution would be to use a context manager.

**Comment by reuterk** [comment]
Thanks, the code was improved by introducting a context manager (though CPython should close the file handle automatically, latest when the instance of the Deer class is destructed).

**Comment by kain88-de** [comment]
> though CPython should close the file handle automatically, latest when the instance of the Deer class is destructed

I thought so too. But some time ago I fixed [similar code](https://github.com/rcsb/mmtf-python/pull/32) in the python-mmtf package that showed a lot of leaked file descriptors in tests of MDAnalysis.
